gpu_variant:
  - None
  - cuda-12                    # [win or (linux and x86_64)]
  - metal                      # [(osx and arm64)]

cuda_compiler_version:
  - None                       
  - 12.8                       # [win or (linux and x86_64)]

zip_keys:                      # [win or (linux and x86_64)]
  -                            # [win or (linux and x86_64)]
    - gpu_variant              # [win or (linux and x86_64)]
    - cuda_compiler_version    # [win or (linux and x86_64)]

c_compiler:
  - vs2022                     # [win]

cxx_compiler:
  - vs2022                     # [win]