gpu_variant:
  - None
  - cuda-12                    # [win or linux]
  - cuda-13                    # [win or linux]
  - metal                      # [(osx and arm64)]

cuda_compiler_version:
  - None                       
  - 12.8                       # [win or linux]
  - 13.0                       # [win or linux]

zip_keys:                      # [win or linux]
  -                            # [win or linux]
    - gpu_variant              # [win or linux]
    - cuda_compiler_version    # [win or linux]